language: go

go:
 - "1.20"

addons:
  sonarcloud:
    organization: "memetoasty"
      

env:
  - GOLANG_PROTOBUF_REGISTRATION_CONFLICT=ignore

install: 
  - make init -f backend/services/register/Makefile

script:
  - cd backend
  - go test -json ./... > report.json
  - go test -coverprofile=coverage.out ./...
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'