language: go

go:
 - "1.20"

# addons:
#   sonarcloud:
#     organization: "sonarcloud"
#     token:
#       secure: ""
      

env:
  - GOLANG_PROTOBUF_REGISTRATION_CONFLICT=ignore

script:
  - cd backend
  - go test -json ./... > report.json
  - go test -coverprofile=coverage.out ./...
  # - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'