name: Scan
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

env:
  GOLANG_PROTOBUF_REGISTRATION_CONFLICT: ignore

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run golang tests
        run: |
          cd backend
          go test -json ./... > report.json
          go test -coverprofile=coverage.out ./...
          cd ..

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -X
          projectBaseDir: ${GITHUB_WORKSPACE}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}